class PollinationsModels {
  static const Map<String, String> imageModels = {
    'flux': 'Flux Schnell (Free)',
    'zimage': 'ZImage (Free)',
    'gptimage': 'GPT Image (Free)',
    'gptimage-large': 'GPT Image Large (Free)',
    'gpt-image-2': 'GPT Image 2 (Premium)',
    'kontext': 'Flux.1 Kontext (Premium)',
    'seedream': 'Seedream (Premium)',
    'seedream-pro': 'Seedream Pro (Premium)',
    'klein': 'Klein (Premium)',
    'p-image': 'P-Image (Premium)',
    'p-image-edit': 'P-Image Edit (Premium)',
    'nanobanana': 'Nanobanana (Premium)',
    'nanobanana-2': 'Nanobanana 2 (Premium)',
    'nanobanana-pro': 'Nanobanana Pro (Premium)',
    'grok-imagine': 'Grok Imagine (Premium)',
    'grok-imagine-pro': 'Grok Imagine Pro (Premium)',
    'ideogram-v4-turbo': 'Ideogram v4 Turbo (Free)',
    'ideogram-v4-balanced': 'Ideogram v4 Balanced (Premium)',
    'ideogram-v4-quality': 'Ideogram v4 Quality (Premium)',
    'wan-image': 'Wan Image (Premium)',
    'wan-image-pro': 'Wan Image Pro (Premium)',
    'nova-canvas': 'Nova Canvas (Free)',
    'qwen-image': 'Qwen Image (Premium)',
    'SANA': 'SANA (FREE)',
  };
}
